name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: snippet
    attributes:
      label: Code snippet
      description: |
        Please provide a minimal code snippet to reproduce the bug. This will be automatically formatted into code, so no need for backticks.
      render: python
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a concise description of the bug.
      placeholder: |
        1. I am attempting to do X.
        2. Expected behavior: ...
        3. Instead, got this behavior: ...
        4. Proposed solution (if any). For extra credit, submit a PR with your solution to contribute to the community.

        Tip: You can attach images or files by dragging them into the text box.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: v2023.1.1
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which OS?
      multiple: true
      options:
        - label: MacOS
        - label: Windows
        - label: Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Please provide any relevant log output, especially error messages. This will be automatically formatted, so no need for backticks.
      render: shell
