name: Feature Request
description: Propose a new idea for this project
title: "[Feature Request]: "
labels: ["feature_request", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this feature request!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Briefly describe your need
      placeholder: I would like to be able to do X.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Detail the solution you'd like to see implemented.
      placeholder: Add functionality that does (1)..., (2)...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: List any alternative solutions, prior art or features you have considered, if any.
      placeholder: E.g. Similar functionality is found in package <Y>.
    validations:
      required: false
