name: Python Linting

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade ruff black mypy

      - name: ruff
        run: |
          ruff --version
          ruff .

      - name: black
        run: |
          black --version
          black --check --diff --color ${{ github.event.repository.name }}

      - name: mypy
        run: |
          mypy --version
          rm -rf .mypy_cache
          mypy ${{ github.event.repository.name }}
