name: Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # maximize CI coverage of different platforms and python versions while minimizing the
        # total number of jobs. We run all pytest splits with the oldest supported python
        # version (currently 3.9) on windows (seems most likely to surface errors) and with
        # newest version (currently 3.12) on ubuntu (to get complete coverage on unix).
        config:
          - os: windows-latest
            python: "3.9"
            resolution: highest
          - os: ubuntu-latest
            python: "3.12"
            resolution: lowest-direct
          - os: macos-latest
            python: "3.10"
            resolution: lowest-direct

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@main

      - name: Create mamba environment
        run: |
          micromamba create -n venv python=${{ matrix.config.python }} --yes

      - name: Install uv
        run: micromamba run -n venv pip install uv

      - name: Install repo and dependencies
        run: |
          micromamba activate venv
          uv pip install --editable '.[ci]' --resolution=${{ matrix.config.resolution }}

      - name: pytest
        run: |
          micromamba activate venv
          pytest tests
